#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
setxkbmap -layout gb,us -option grp:shifts_toggle &
feh --bg-scale /home/ross/Pictures/wallpaper2.jpg &
/usr/bin/gentoo-pipewire-launcher &
picom &
polybar main &
wmname LG3D &
blueman-applet &
solaar &&
./AppImage/filen_x86_64.AppImage &
flatpak run ch.protonmail.protonmail-bridge &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width        1
bspc config window_gap          2
bspc config top_padding         32


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
